Traceback (most recent call last):
  File "/home/mahasiswa1/meds-distribution/main_pymoo.py", line 100, in <module>
    run()
    ~~~^^
  File "/home/mahasiswa1/meds-distribution/main_pymoo.py", line 86, in run
    res = minimize(problem_intf, algo, termination=termination,
                   seed=1,
                   verbose=True)
  File "/home/mahasiswa1/miniconda3/lib/python3.13/site-packages/pymoo/optimize.py", line 67, in minimize
    res = algorithm.run()
  File "/home/mahasiswa1/miniconda3/lib/python3.13/site-packages/pymoo/core/algorithm.py", line 138, in run
    self.next()
    ~~~~~~~~~^^
  File "/home/mahasiswa1/miniconda3/lib/python3.13/site-packages/pymoo/core/algorithm.py", line 158, in next
    self.evaluator.eval(self.problem, infills, algorithm=self)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mahasiswa1/miniconda3/lib/python3.13/site-packages/pymoo/core/evaluator.py", line 69, in eval
    self._eval(problem, pop[I], evaluate_values_of, **kwargs)
    ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mahasiswa1/miniconda3/lib/python3.13/site-packages/pymoo/core/evaluator.py", line 90, in _eval
    out = problem.evaluate(X, return_values_of=evaluate_values_of, return_as_dictionary=True, **kwargs)
  File "/home/mahasiswa1/miniconda3/lib/python3.13/site-packages/pymoo/core/problem.py", line 257, in evaluate
    _out = self.do(X, return_values_of, *args, **kwargs)
  File "/home/mahasiswa1/miniconda3/lib/python3.13/site-packages/pymoo/core/problem.py", line 297, in do
    self._evaluate_elementwise(X, out, *args, **kwargs)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mahasiswa1/miniconda3/lib/python3.13/site-packages/pymoo/core/problem.py", line 315, in _evaluate_elementwise
    elems = self.elementwise_runner(f, X)
  File "/home/mahasiswa1/miniconda3/lib/python3.13/site-packages/pymoo/core/problem.py", line 32, in __call__
    return [f(x) for x in X]
            ~^^^
  File "/home/mahasiswa1/miniconda3/lib/python3.13/site-packages/pymoo/core/problem.py", line 25, in __call__
    self.problem._evaluate(x, out, *self.args, **self.kwargs)
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mahasiswa1/meds-distribution/pymoo_interface/hvrp3l_opt.py", line 196, in _evaluate
    total_cost = self.get_total_cost_without_decoding(x)
  File "/home/mahasiswa1/meds-distribution/pymoo_interface/hvrp3l_opt.py", line 181, in get_total_cost_without_decoding
    routes = get_routes_from_x(x, self.hvrp3l_instance)
  File "/home/mahasiswa1/meds-distribution/pymoo_interface/hvrp3l_opt.py", line 31, in get_routes_from_x
    routes[vi].append(cust_idx)
    ~~~~~~^^^^
IndexError: list index out of range
