Traceback (most recent call last):
  File "/home/mahasiswa1/meds-distribution/main_avns.py", line 94, in <module>
    run()
    ~~~^^
  File "/home/mahasiswa1/meds-distribution/main_avns.py", line 79, in run
    solution = avns.solve(problem)
  File "/home/mahasiswa1/meds-distribution/avns/avns.py", line 41, in solve
    self.reset(problem)
    ~~~~~~~~~~^^^^^^^^^
  File "/home/mahasiswa1/meds-distribution/avns/avns.py", line 33, in reset
    self.curr_solution = saving(problem)
                         ~~~~~~^^^^^^^^^
  File "/home/mahasiswa1/meds-distribution/avns/saving.py", line 51, in saving
    raise ValueError()
ValueError
